repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: poetry-check
        name: Check pyproject.toml structure
        entry: poetry check
        language: system
        types: [python]

      - id: check-lockfile-sync
        name: Ensure lockfile matches TOML
        entry: poetry lock --check
        language: system
        types: [python]
